//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MistikRota.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MistikRota.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string çıkış {
            get {
                return ResourceManager.GetString("çıkış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamı....
        /// </summary>
        public static string devamı {
            get {
                return ResourceManager.GetString("devamı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string dil {
            get {
                return ResourceManager.GetString("dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Beğenilenler.
        /// </summary>
        public static string enbeğenilenler {
            get {
                return ResourceManager.GetString("enbeğenilenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string giriş {
            get {
                return ResourceManager.GetString("giriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string hakkımızda {
            get {
                return ResourceManager.GetString("hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ekle.
        /// </summary>
        public static string kategoriekle {
            get {
                return ResourceManager.GetString("kategoriekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string kategoriler {
            get {
                return ResourceManager.GetString("kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string ketegorileradmin {
            get {
                return ResourceManager.GetString("ketegorileradmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ekle.
        /// </summary>
        public static string kullanıcıekle {
            get {
                return ResourceManager.GetString("kullanıcıekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string kullanıcılar {
            get {
                return ResourceManager.GetString("kullanıcılar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mistik Rota.
        /// </summary>
        public static string mistikrota {
            get {
                return ResourceManager.GetString("mistikrota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öykü Ekle.
        /// </summary>
        public static string öyküekle {
            get {
                return ResourceManager.GetString("öyküekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öykülerim.
        /// </summary>
        public static string öykülerim {
            get {
                return ResourceManager.GetString("öykülerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili Düzenle.
        /// </summary>
        public static string profilidüzenle {
            get {
                return ResourceManager.GetString("profilidüzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili Göster.
        /// </summary>
        public static string profiligöster {
            get {
                return ResourceManager.GetString("profiligöster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili Sil.
        /// </summary>
        public static string profilisil {
            get {
                return ResourceManager.GetString("profilisil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Yazılar.
        /// </summary>
        public static string sonyazilar {
            get {
                return ResourceManager.GetString("sonyazilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string tümü {
            get {
                return ResourceManager.GetString("tümü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string üyeol {
            get {
                return ResourceManager.GetString("üyeol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim.
        /// </summary>
        public static string yönetim {
            get {
                return ResourceManager.GetString("yönetim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string yorumlar {
            get {
                return ResourceManager.GetString("yorumlar", resourceCulture);
            }
        }
    }
}
